# Generated by Django 3.2.6 on 2021-08-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, help_text='Username (login)', max_length=255, unique=True)),
                ('email', models.EmailField(db_index=True, help_text='Email of user', max_length=254, unique=True)),
                ('avatar', models.URLField(help_text='Avatar image', null=True)),
                ('is_active', models.BooleanField(db_column='isActive', default=True, help_text='Is active user')),
                ('is_staff', models.BooleanField(db_column='isStaff', default=False, help_text='Is superuser')),
                ('role', models.CharField(blank=True, choices=[('admin', 'admin'), ('developer', 'developer'), ('guest', 'guest')], help_text='Role of user', max_length=15, null=True)),
            ],
        ),
    ]
